require 'puppet-lint/tasks/puppet-lint'

PuppetLint.configuration.send("disable_80chars")
PuppetLint.configuration.send("disable_selector_inside_resource")
PuppetLint.configuration.send("disable_double_quoted_strings")
PuppetLint.configuration.send("disable_case_without_default")
PuppetLint.configuration.send("disable_trailing_whitespace")
